apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telovix-console.fullname" . }}-secret
  labels:
    {{- include "telovix-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
  {{- if .Values.bootstrap.adminEmail }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.bootstrap.adminEmail | quote }}
  BOOTSTRAP_ADMIN_PASSWORD_HASH: {{ .Values.bootstrap.adminPasswordHash | quote }}
  {{- end }}
  {{- if .Values.bootstrap.licenseBundle }}
  BOOTSTRAP_LICENSE_BUNDLE: {{ .Values.bootstrap.licenseBundle | quote }}
  {{- end }}
