apiVersion: v1
kind: Service
metadata:
  name: {{ include "telovix-console.fullname" . }}
  labels:
    {{- include "telovix-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.sensorPort }}
      targetPort: sensor
      protocol: TCP
      name: sensor
  selector:
    {{- include "telovix-console.selectorLabels" . | nindent 4 }}
