{{- if and .Values.imageCredentials.username .Values.imageCredentials.password (not .Values.existingPullSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telovix-sensor.pullSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telovix-sensor.labels" . | nindent 4 }}
  annotations:
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
