{{- if and (not .Values.sensor.existingSecret) .Values.sensor.enrollmentToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telovix-sensor.fullname" . }}-enrollment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telovix-sensor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  enrollmentToken: {{ .Values.sensor.enrollmentToken | quote }}
{{- end }}
